### ISSUE TITLE
V4: DDO Typings

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#1091]
Create DDO

**Comment by kremalicious** [comment]
For reference, have put them together without any further JSDoc documentation over on market based on what we have in https://github.com/oceanprotocol/docs/pull/783, so could be copied over and then properly imported/exported:  

https://github.com/oceanprotocol/market/pull/941

**Comment by kremalicious** [comment]
more findings:

Most remaining refactor issues for new DDO in market v4 are around:
1. `ddo.findServiceByType()` access
2. `ddo.dataTokenInfo` access, like, a lot of it

I think for 1 we can simply ditch the overcomplicating of `DDO` in ocean.js. This whole making JSON "into a DDO" which just means adding methods to it seems unnecessary as metadata part can be now accessed with `ddo.metadata`, and the rest is a one-liner `array.filter()` in JavaScript. So `DDO` becomes just exported typings as issue title suggests.

2. for this one solution would be to put back all the datatoken info but in the service [as suggested here](https://github.com/oceanprotocol/docs/pull/783#discussion_r741057632) so that decision would first need to be taken over in the spec. But most likely we need to rethink a bit how we use datatoken display, and in utility methods in market as now the NFT represents the actual dataset and not the datatoken.

And I would make the DDO typing here reflect the Aquarius response and not just the original spec, meaning we add here `stats` & `events` which we want to remove from the pure DDO spec. So we should also document in code that those objects are added by Aquarius so people don't think they need to add them when constructing a new DDO for publishing.

**Comment by mihaisc** [comment]
1. doesn't make sense , remove it
2. we could add that there in aquarius or just fetch it from the graph. Regarding nft already wrote a comment on the ddo issue.
We should have two objects here as well `DDO` and `Asset` (i like this more that `AquariusResponse`) , `Asset` inherits `DDO`. `Asset` is what `Aquarius` returns.

**Comment by kremalicious** [comment]
nice, I like it, as it's way easier to explain à la "`DDO` is what's on chain/gets hashed and `Asset` is what `Aquarius` returns"
