### ISSUE TITLE
Use sticky/fixed navigation

### ISSUE THREAD

**Issue by ReangeloJ** [oceanprotocol/ocean.js#589]
**Is your feature request related to a problem? Please describe.**
When scrolling on pc and mobile the navigation stays at the top. When a user has scrolled quite some bit, it becomes annoying to quickly navigate to another page. This is especially the case on mobile devices.

**Describe the solution you'd like**
I would suggest creating a sticky / fixed navigation so users can navigate the site more easily. Or if this is not desired, then a floating scroll to top button somewhere in the lower corners, to make it easier and faster to scroll back up.

**Comment by kremalicious** [comment]
Thanks for the input, much appreciated! Good points but this is always a trade-off on mobile because screen space is precious and any fixed element would distract from the actual content (fixed main nav), or might overlay something users want to interact with (scroll-to-top button). The user flow described here only covers a flow where users browse through multiple pages of the site. But another job-to-be-done flow would be users arriving at a specific page and are interested in its content only. And for that, any fixed element would be distracting.

So our approach is to have navigation at top & bottom only and rather have in-page navigation to guide users like on the `/technology/**` pages, as to prioritize content over navigation. Although I agree we could do a better job with that footer navigation. For all other use cases, we leave it to core OS functionality. E.g. on iOS Safari, tapping above the address bar scrolls to the top on any webpage.

For those reasons I don't see this as a priority right now so will close this.
