### ISSUE TITLE
Add ocean.assets.isConsumable

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.js#759]
This function should check if the asset is consumable by :
- check isDisabled flag (it exists & true -> asset is not consumable)
- check file conectivity
- check file length (optional)
- check credentials

Return should be a interface, containing a status and a status_message: Eg
   0, All good
   1, Asset is disabled
   2. Asset is empty
   3, Connectivity check failure
   4, Credential missing from allow list
   5, Credential found on deny list

**Comment by krisliew** [comment]
@alexcos20  for check file connectivity and file length, we should remove it from this issue since we are doing that on market as discussed yesterday. So the new action plan now should be like this below:

This function should check if the asset is consumable by :

- check isDisabled flag (it exists & true -> asset is not consumable)
- check credentials

Return should be a interface, containing a status and a status_message: Eg
0, All good
1, Asset is disabled
2, Credential missing from allow list
3, Credential found on deny list
